# Generated by Django 5.1 on 2025-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAnnouncement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('target_role', models.CharField(blank=True, max_length=20, null=True)),
                ('is_admin_announcement', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student_announcement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'student_assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'student_attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalCollege',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'student_college',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('professor_email', models.EmailField(max_length=254)),
                ('year', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'student_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalCourseMark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_score', models.FloatField()),
                ('midterm_score', models.FloatField()),
                ('final_score', models.FloatField()),
            ],
            options={
                'db_table': 'student_coursemark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'student_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('program_type', models.CharField(max_length=10)),
                ('duration_years', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'student_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_year', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'student_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField()),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student_submission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('department', models.IntegerField(null=True)),
                ('designation', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(null=True)),
                ('professor_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
    ]
