# Generated by Django 5.1 on 2025-04-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professorassignment_professormaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCourseMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='materials/')),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'student_coursematerial',
                'managed': False,
            },
        ),
    ]
