# Generated by Django 5.1 on 2025-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_externalcoursematerial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
            options={
                'db_table': 'student_enrollment',
                'managed': False,
            },
        ),
    ]
