# Generated by Django 5.1 on 2025-04-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_externalenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAdminAnnouncement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_by', models.CharField(max_length=255)),
                ('created_by_role', models.CharField(default='admin', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_adminannouncement',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TimetableEntry',
        ),
    ]
