# Generated by Django 5.1 on 2025-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_submission_status_alter_submission_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file_url',
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
